language: java

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dsign.skip=true -B -V

stages:
  - test
  - name: integration-test
  - name: release
    if: tag IS present AND branch = master

jobs:
  include:
    - stage: test
    - stage: release
      script: mvn clean package -Dmaven.test.skip=true sign:sign deploy:deploy -B

jdk:
  - openjdk11
